/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import proyecto.ListaRelaciones;
import proyecto.Listas;
import Grafos.MatrizAdyacencia;
import javax.swing.JOptionPane;
import proyecto.ListaUsuario;
/**
 *
 * @author Jennifer Pérez
 */
public class VentanaCantidadISlas extends javax.swing.JFrame {
    
    Listas listas;
    MatrizAdyacencia matrizAdy;
    ListaRelaciones lr;
    /**
     * Creates new form CantidadIslas
     */
    public VentanaCantidadISlas(Listas listas) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listas = listas;
        this.lr = listas.getListaRelaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DSF = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DSF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DSF.setText("DFS");
        DSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSFActionPerformed(evt);
            }
        });
        jPanel1.add(DSF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 140, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("BFS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 140, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Seleccione el método con el que desee recorrer el grafo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Recorridos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 250, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new VentanaGeneral(listas).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSFActionPerformed

        ListaUsuario lu = listas.getListaUsuario();
        matrizAdy = new MatrizAdyacencia(lu.getTamano());
        
        String[] rutas = listas.getListaRelaciones().getArrayRelacion();

        for (int i = 0; i < rutas.length; i++) {
            System.out.println();
            matrizAdy.agregarVert(lu.getPosicion(Integer.parseInt(rutas[i].split(",")[0])), lu.getPosicion(Integer.parseInt(rutas[i].split(",")[1])));
            matrizAdy.agregarVert(lu.getPosicion(Integer.parseInt(rutas[i].split(",")[1])), lu.getPosicion(Integer.parseInt(rutas[i].split(",")[0])));
            
        }
        matrizAdy.imprimirMatriz();
        JOptionPane.showMessageDialog(null, "Ingeniero trabajando en la función");
        
        int[][] matriz = matrizAdy.getMatrizSP();
        
    }//GEN-LAST:event_DSFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Ingeniero trabajando en la función");
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DSF;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
